# ========================
# NITAZENEMAP CONFIG
# ========================
# This file controls how the pipeline runs. Update paths and parameters as needed.

# ---- SETTINGS ----
benzo_substring_list: ['benzo', 'zepine', 'zolam', 'zepoxide', 'zepam', 'azapine', 'blues', 'zapam',
                        #generic
                        'diazepam', 'diaze', 'MSJ', 'daizepam', 'diaepam', 'diaezpam', 'bensedin', 'valium', 'valum', 'msj', 'martin dcw', 'martin dow',
                        #vallies
                        'alprazolam', 'xanax', 'xanac', 'alpraz', 'xanx', 
                        #clonazepam
                        'clonazepam', 'clonaz', 'klonapin', 'ksalol', 'ksol', 'rivotril',
                        #prodrugs
                        'zafone']
diazepam_substring_list: ['diazepam', 'diaze', 'MSJ', 'daizepam', 'diaepam', 'diaezpam', 'bensedin', 'valium', 'valum', 'msj', 'martin dcw', 'martin dow']
alprazolam_substring_list: ['alprazolam', 'xanax', 'xanac', 'alpraz', 'xanx']
clonazepam_substring_list: ['clonazepam', 'klonopin', 'klonapin', 'ksalol', 'ksol', 'rivotril']
nitazene_substring_list: ['nitazene', 'nitazepipne', 'nitazepyne', 'metonitazene', 'metonitazepine', 'metonitazepyne', 'metonitazepipne']

# ---- FILE PATHS ----
dataPath: data                                                      # Directory for stored data
#processedPath: data/processed                                       # Directory for processed files (i.e., those which can optionally be used as-is for input or independently generated by the user).
#outPath: data/output                                                # Directory for outputs
plotsPath: data/plots                                               # Directory for plots

# ---- CONFIGUATION OPTIONS ----
saveData: True

# ---- PLOT OPTIONS ----
saveFigures: False                                                   # Save figures as a png image in the outPath (True/False)
dpi: 300              