# ========================
# NITAZENEMAP CONFIG
# ========================
# This file controls how the pipeline runs. Update paths and parameters as needed.

# ---- SETTINGS ----
benzo_substring_list: ['benzo','benzos', 'zepine', 'zolam', 'zepoxide', 'zepam', 'azapine', 'blues', 'zapam',
                        #generic
                        'diazepam', 'diaze', 'MSJ', 'daizepam', 'diazapam', 'diaepam', 'diaezpam', 'bensedin', 'valium', 'valum', 'msj', 'martin dcw', 'martin dow',
                        #vallies
                        'alprazolam', 'xanax', 'xanac', 'alpraz', 'xanx', 'alpprazolam', 
                        #clonazepam
                        'clonazepam', 'clonazapam', 'clonaz', 'klonapin', 'ksalol', 'ksol', 'rivotril',
                        #prodrugs
                        'zafone']
not_benzo_substring_list: ['benzoylecgonine','benzocaine']
opioid_substring_list: ['oxy','opioid','opiate','codone','adol','adone','morph','ophine','orphine','orphan','ezitramide',
                        'thebacon','papaverine','6-MAM','6 Monoacetyl','oxycontin','oxydolor', #note: 'oxy' will cross-react with other non-opioid drugs, must use not_opioid_substring_list!
                        'fentanil','fentanyl','heroin','codeine',
                        'nitazene','nitazepyne','nitazepipne',
                        #rogue ones
                        'naltrexamine','metopon',
                        #kratom
                        'kratom','mitragynine']
not_opioid_substring_list: ['hydroxybutyr','oxyphenethylamine','oxyamphetamine','oxyqualone','oxyapatite','oxycillin','oxymethoxetamine']
heroin_substring_list: ['heroin','herion','heorin','diamorphine','diacetylmorphine']
diazepam_substring_list: ['diazepam', 'diaze', 'MSJ', 'daizepam', 'diaepam', 'diazapam', 'diaezpam', 'bensedin', 'valium', 'valum', 'msj', 'martin dcw', 'martin dow']
alprazolam_substring_list: ['alprazolam', 'xanax', 'xanac', 'alpraz', 'xanx', 'alpprazolam']
clonazepam_substring_list: ['clonazepam', 'clonazapam', 'cloonazepam', 'klonopin', 'klonapin', 'ksalol', 'ksol', 'rivotril']
nitazene_substring_list: ['nitazene', 'nitazepipne', 'nitazepyne', 'metonitazene', 'metonitazepine', 'metonitazepyne', 'metonitazepipne']
orphine_substring_list: ['cyclorphine', 'brorphine', 'chlorphine', 'iodorphine', 'fluorphine', 'cybrorphine', 'cymethorphine', 'ezitramide', 'spirorphine', 'spiroxatrine','ophine']
adrenergic_list: ['medetomidine','xylazine','clonidine','guanfacine','tizanidine','guanabenz']
othernovelbenzos_list: ['clobromazolam', 'clonazolam', 'desalkylgidazepam','methylclonazepam','meclonazepam','rilmazafone','flubromazolam','flubromazepam','nitrazolam','flualprazolam']
vapes_substring_list: ['vape']
SCRA_substring_list: ['icana','adb','mdmb','apica','k2','spice','bioca','ethiodone',
                      # series
                      'am-','amb-','akb-','az-','azd-','cp-','fab-','hu-','jwh','pb-','rcs-','sts-','thj-','ur-','win-','win ','xlr-',
                      # individual ones
                      'o-585','o-689','cumyl-bica','cumyl-cbmica','org 28312', 'org 28611','a-796,260', 'a-834,735']
cannabinoids_substring_list: ['cannabinol', 'thc', 'cannabigerol','nabilone','dronabinol']
psychedelics_substring_list: ['dmt','nboh','nbome','psilocybin','psilocin','lsd','lysergic acid']

# ---- FILE PATHS ----
dataPath: data                                                       # Directory for stored data
#previousyearsPath: data/previous_years
#processedPath: data/processed                                       # Directory for processed files (i.e., those which can optionally be used as-is for input or independently generated by the user).
outPath: data/out                                                # Directory for outputs
plotsPath: data/plots                                               # Directory for plots

# ---- CONFIGUATION OPTIONS ----
saveData: True

# ---- PLOT OPTIONS ----
saveFigures: False                                                   # Save figures as a png image in the outPath (True/False)
dpi: 300              